server:
  port: 7902

spring:
  application:
    name: microservice-consumer-movie-feign
eureka:
  client:
    serviceUrl:
#      defaultZone: http://user:password@localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true